const SET_CHAT_LOADING_TRUE = "SET_CHAT_LOADING_TRUE";

const SET_DATING_MESSAGES = "SET_DATING_MESSAGES";
const SET_DATING_NOTIFICATIONS = "SET_DATING_NOTIFICATIONS";
const SET_DATING_LIKED_NOTIFICATIONS = "SET_DATING_LIKED_NOTIFICATIONS";
const SET_DATING_UNLIKED_NOTIFICATIONS = "SET_DATING_UNLIKED_NOTIFICATIONS";


export default {
    SET_CHAT_LOADING_TRUE,


    SET_DATING_MESSAGES,
    SET_DATING_NOTIFICATIONS,
    SET_DATING_LIKED_NOTIFICATIONS,
    SET_DATING_UNLIKED_NOTIFICATIONS,

}