export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";


export const GET_CURRENT_SECTION = "GET_CURRENT_SECTION";
export const SET_CURRENT_SECTION = "SET_CURRENT_SECTION";

