const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";

const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";
const SET_DATING_USER_PROFILE = "SET_DATING_USER_PROFILE";
const SET_ACCOMMODATION_USER_PROFILE = "SET_ACCOMMODATION_USER_PROFILE";
const SET_TENANT_USER_PROFILE = "SET_TENANT_USER_PROFILE";

const GET_CURRENT_SECTION = "GET_CURRENT_SECTION";
const SET_CURRENT_SECTION = "SET_CURRENT_SECTION";

const SET_USER_ID = "SET_USER_ID";

export default {
    GET_PROFILE_REQUEST,
    GET_PROFILE_SUCCESS,
    GET_PROFILE_FAILURE,
    SET_DATING_USER_PROFILE,
    SET_ACCOMMODATION_USER_PROFILE,
    SET_TENANT_USER_PROFILE,
    INCREMENT,
    DECREMENT,
    GET_CURRENT_SECTION,
    SET_CURRENT_SECTION,
    SET_USER_ID,
}