const SET_LOADING_TRUE = "SET_LOADING_TRUE";
const SET_USER_SUCCESS = "SET_USER_SUCCESS";
const SET_USER_FAILURE = "SET_USER_FAILURE";

const GET_ACCOMMODATION_USER_PROFILE = "GET_ACCOMMODATION_USER_PROFILE";
const SET_ACCOMMODATION_USER_PROFILE_SUCCESS = "SET_ACCOMMODATION_USER_PROFILE_SUCCESS";
const SET_ACCOMMODATION_USER_PROFILE_FAIL= "SET_ACCOMMODATION_USER_PROFILE_FAIL";

const GET_TENANT_USER_PROFILE = "GET_TENANT_USER_PROFILE";
const SET_TENANT_USER_PROFILE_SUCCESS = "SET_TENANT_USER_PROFILE_SUCCESS";
const SET_TENANT_USER_PROFILE_FAIL= "SET_TENANT_USER_PROFILE_FAIL";

const GET_USER_DATING_PROFILE = "GET_USER_DATING_PROFILE";
const SET_USER_DATING_PROFILE_SUCCESS = "SET_USER_DATING_PROFILE_SUCCESS";
const SET_USER_DATING_PROFILE_FAIL = "SET_USER_DATING_PROFILE_FAIL";

const GET_CANDIDATE_DATING_PROFILE = "GET_CANDIDATE_DATING_PROFILE";
const SET_CANDIDATE_DATING_PROFILE_SUCCESS = "SET_CANDIDATE_DATING_PROFILE_SUCCESS";
const SET_CANDIDATE_DATING_PROFILE_FAIL = "SET_CANDIDATE_DATING_PROFILE_FAIL";
const GET_MATCHING_CANDIDATES_IDS = "GET_MATCHING_CANDIDATES_IDS";
const SET_MATCHING_CANDIDATES_IDS = "SET_MATCHING_CANDIDATES_IDS";
const SHELF_REVIEWED_USER_DATA = "SHELF_REVIEWED_USER_DATA";

export default {
    SET_LOADING_TRUE,
    SET_USER_SUCCESS,
    SET_USER_FAILURE,
    GET_ACCOMMODATION_USER_PROFILE,
    SET_ACCOMMODATION_USER_PROFILE_SUCCESS,
    SET_ACCOMMODATION_USER_PROFILE_FAIL,

    GET_TENANT_USER_PROFILE,
    SET_TENANT_USER_PROFILE_SUCCESS,
    SET_TENANT_USER_PROFILE_FAIL,

    GET_USER_DATING_PROFILE,
    SET_USER_DATING_PROFILE_SUCCESS,
    SET_USER_DATING_PROFILE_FAIL,
    GET_CANDIDATE_DATING_PROFILE,
    SET_CANDIDATE_DATING_PROFILE_SUCCESS,
    SET_CANDIDATE_DATING_PROFILE_FAIL,
    GET_MATCHING_CANDIDATES_IDS,
    SET_MATCHING_CANDIDATES_IDS,
    SHELF_REVIEWED_USER_DATA,

}