# сейчас проект настроен на то, что будет выполняться hibernate_boot создание таблиц в БД
# и, затем выполнятся файлы  schema.sql  и data.sql
# для справки:
#    https://www.baeldung.com/spring_boot_data_sql_and_schema_sql

server:
  port: 8000
spring:
  sql:
    init:
#      mode: never
      mode: always
  h2:
    console:
      enabled: true
      settings:
        trace: false
___
spring:
  profiles:
    active:  dev
___
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver_class_name: org.h2.Driver
  jpa:
    defer_datasource_initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      generate_ststistics: true
    generate_ddl: true
    hibernate:
      ddl_auto: create_drop
  config:
    activate:
      on_profile: dev
___
spring:
#    для включения авто_ заполнения БД, в физическую (не h2 базу) еще нужно добавить:
  sql:
    init:
#      mode: never
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/book_db....????
    username:
    password:
    driver_class_name: org.postgresql.Driver
  jpa:
    database: postgresql
    defer_datasource_initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_ddl: true
      generate_ststistics: false
    show_sql: false
    hibernate:
      # https://russianblogs.com/article/85481550836/    ,  https://docs.spring.io/spring_boot/docs/1.1.0.M1/reference/html/howto_database_initialization.html
       ddl_auto: update
  config:
    activate:
      on_profile: prod
