# сейчас проект настроен на то, что будет выполняться hibernate-boot создание таблиц в БД
# и, затем выполнятся файлы  schema.sql  и data.sql
# для справки:
#    https://www.baeldung.com/spring-boot-data-sql-and-schema-sql


server:
  port: 8000
spring:
  #  config:
  #    import: optional:file:secrets.properties[.properties]
  h2:
    console:
      enabled: true   # http://localhost:8000/h2-console/
      settings:
        trace: false
logging: # https://habr.com/ru/post/521950/
  level:
    root: info
    com: error
    org: error
#    file: appLog.log

---
spring:
  profiles:
    active: local
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          time_zone: UTC
---
spring:
  config:
    activate:
      on-profile: local
    import: optional:secrets.properties[.properties]

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
#        для пакетной отправки фотографий:
        jdbc:
          batch_size: 40
#        тоже для пакетной отправки фотографий:
        order_updates: true
        #        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
#        generate_statistics: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
#spring.jpa.properties.hibernate.generate_statistics=true
jwt:
#  secret: ${JWT_SECRET:""}
#  secretRefresh: ${JWT_SECRET_REFRESH}
#  secretPasswordReset: ${JWT_SECRET_PASSWORD_RESET}
#  secretPasswordUpdate: ${JWT_SECRET_PASSWORD_UPDATE}

  header: Authorization
  expiration: 7200
  expirationRefresh: 604800
  expirationPasswordReset: 86400
  expirationPasswordUpdate: 3600

#
#  header: Authorization
#  expiration: ${6*1200}                      #6 часов   =7200 сек
#  expirationRefresh: ${3*7*24*1200}          #3 недели  =604800 сек
#  expirationPasswordReset: ${3*24*1200}      #3 дня     =86400 сек
#  expirationPasswordUpdate: ${3*1200}        #3 часа    =3600 сек
#

aws:
#  access-key-id: ${AWS_ACCESS_KEY_ID}
#  access-secret-key: ${AWS_SECRET_KEY}
---
spring:
  #    для включения авто_ заполнения БД, в физическую (не h2 базу) еще нужно добавить:
  sql:
    init:
      #      mode: never
      mode: always  #always - для самой первой заливки данных в БД
  datasource:
    url: jdbc:postgresql://localhost:5432/book_db....????
    username:
    password:
    driver_class_name: org.postgresql.Driver
  jpa:
    database: postgresql
    defer_datasource_initialization: true # true оставить ТОЛЬКО для самого первого запуска, когда в пустую БД заливаем данные! далее сделать false
    #    defer_datasource_initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_ddl: true
      generate_statistics: false
    show_sql: false
    hibernate:
      # https://russianblogs.com/article/85481550836/    ,  https://docs.spring.io/spring_boot/docs/1.1.0.M1/reference/html/howto_database_initialization.html
      ddl_auto: update
  config:
    activate:
      on_profile: prod


