package com.hub.accommodation.domain.user;

public enum Goals {
    NOT_CHOSEN,
    FAMILY_BIRTH_OF_CHILDREN,
    FAMILY_NO_BIRTH_OF_CHILDREN,
    JOINT_RENT_OF_APARTMENT,
    MAKING_FRIENDS_NO_RELATIONSHIP,
    I_AM_SIMPLY_BORED,SPONSORSHIP_WANTED,
    SPONSORSHIP_OFFERED,
    WANTED_WITH_SIMILAR_INTERESTS,
    NOT_YET_DECIDED,
    WANT_TO_RELOCATE, OTHER
    }
