package com.hub.accommodation.domain.user;

public enum Goals {
    TO_BUILD_FAMILY_WITH_CHILDREN,TO_BECOME_A_COUPLE_WITHOUT_CHILDREN,JOINT_RENT_OF_APARTMENT,MAKING_FRIENDS_ONLY,I_AM_JUST_BORED,SPONSORSHIP_BASED_RELATIONSHIP,WANTED_WITH_SIMILAR_INTERESTS
    }
