GET http://localhost:8000/api/v1/accommodations/1
###



POST http://localhost:8000/api/v1/accommodations
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2bGFkQHVrci5uZXQiLCJyb2xlIjoiVVNFUiIsImlkIjoxLCJpYXQiOjE2NDkyNDEwMzksImV4cCI6MTY0OTI0ODIzOX0.WgBVTVZku7BML06dmdlAZJjN27ADe27hBtJo6aFb9Rw

{
"country": 190,
"street" : "Zhukova",
"accommodationType" : 1,
"numberOfRooms" : 2,
"numberOfBeds"  : 3,
"priceTotal"  : 0,
"pricePerRoom"  : 0,
"pricePerPerson"  : 0,
"helpWithWork"  : false,
"helpWithFood"  : false,
"status"  : 1,
"userId"  : 1
}

###
