POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
"email": "vlad@ukr.net",
"password": "123",
"name": "Влад",
"lastName" :"Рябушкин",
"avatar": "https://res.cloudinary.com/vladry/image/upload/v1628498611/vlad_shrunk/vlad_in_car_rtzqzp.jpg"
}
###

POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "email": "rvy@ukr.net",
  "password": "123",
  "name" : "Rvy",
  "lastName" : ""
}
###

POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
"email": "vlad@ukr.net",
"password": "123"
}
###



POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "rvy@ukr.net",
  "password": "123"
}
###


POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "name": "Vlad",
  "lastName" :"Ry",
  "phoneNumber" : "+380675094252",
  "urlSocial1" :"URL1",
  "urlSocial2" : "URL2",
  "messenger1" :"@messanger1",
  "messenger2" : "@messanger2",
  "location" :"Kyiv",
  "hideSocialContactData" : true,
  "datingServiceParticipation" : true,
  "email": "1vlad@ukr.net",
  "password": "123",
  "avatar": "https://res.cloudinary.com/vladry/image/upload/v1628196607/avatars/Vlad_avatar_tjrcut.jpg"
}
###

POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
"email": "vlad@ukr.net",
"password": "rvy"
}
###