POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
"email": "vlad@ukr.net",
"password": "rvy"
}
###
POST http://localhost:8000/api/v1/auth/registerFullUser
Content-Type: application/json

{
  "email": "vlad@ukr.net",
  "password": "rvy"
}
###
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
"email": "vlad@ukr.net",
"password": "rvy"
}
###

POST http://localhost:8000/api/v1/auth/registerFullUser
Content-Type: application/json

{
  "name": "Vlad",
  "lastName" :"Ry",
  "phoneNumber" : "+380675094252",
  "urlSocial1" :"URL1",
  "urlSocial2" : "URL2",
  "messenger1" :"@messanger1",
  "messenger2" : "@messanger2",
  "location" :"Kyiv",
  "hideSocialContactData" : true,
  "datingServiceParticipation" : true,
  "email": "vlad@ukr.net",
  "password": "rvy"
}
###

POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
"email": "vlad@ukr.net",
"password": "rvy"
}
###