GET http://localhost:8000/api/v1/users/photos/all/19?serviceGroup=DATING

### findAllPhotosByUserIdAndServiceGroup

GET http://localhost:8000/api/v1/users/photos?url=url1

### findOnePhotoByUrl

POST http://localhost:8000/api/v1/users/photos/19?serviceGroup=DATING
Content-Type: application/json

[
  "url00",
  "url01",
  "url02",
  "url03",
  "url04",
  "url05",
  "url06"
]

###  saveAllPhotos


PUT http://localhost:8000/api/v1/users/photos/19?serviceGroup=DATING&url=saveOnePhoto
Content-Type: application/json

###  saveOnePhoto

DELETE http://localhost:8000/api/v1/users/photos?url=url1
Content-Type: application/json

###  deleteOnePhotoByUrl


DELETE http://localhost:8000/api/v1/users/photos/19?serviceGroup=DATING
Content-Type: application/json

###  deleteAllPhotosInGroup









