GET http://localhost:8000/api/v1/users/all
###


POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
"name" : "Vlad2",
"lastName" : "Ryab",
  "password": "pas_ryavlad",
"email" : "21rvy@ukr.net",
"phoneNumber" : "+380637400791",
"hideSocialContactData": true,
"urlSocial1": "facebook.com/VladFromUkraine",
"urlSocial2" : "",
"messenger1" : "@Vlad",
"messenger2" : "",
"city" : "Kiev",
"cityRegion" : "Kievsky", "country" : 1,
"datingServiceParticipation" : false
}
###


GET http://localhost:8000/api/v1/users/1
###
GET http://localhost:8000/api/v1/users/1/datingProfile
###

GET http://localhost:8000/api/v1/users/?email=rvy@ukr.net
###
GET http://localhost:8000/api/v1/users/?email=vlad@ukr.net
###

GET http://localhost:8000/api/v1/users/profile
###

POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
  "name" : "Matvey",
  "lastName" : "Kot",
  "password": "pas_ryavlad",
  "email" : "213rvy@ukr.net",
  "phoneNumber" : "+380637400791",
  "hideSocialContactData": true,
  "urlSocial1": "facebook.com/VladFromUkraine",
  "urlSocial2" : "",
  "messenger1" : "@Vlad",
  "messenger2" : "",
  "city" : "Kiev",
  "cityRegion" : "Kievsky", "country" : 1,
  "datingServiceParticipation" : false,
  "avatar": "https://res.cloudinary.com/vladry/image/upload/v1628498610/vlad_shrunk/cat2_x0yqxm.jpg"
}
###