package com.hub.accommodation.domain.dating.ChatSettings;

public enum InterlocutorStatusEnum {

    BLOCKED_CORRESPONDENCE_HIDDEN_FOR_ALL,
    BLOCKED_CORRESPONDENCE_AVAILABLE_FOR_ALL,
    BLOCKED_CORRESPONDENCE_AVAILABLE_FOR_RECIPIENT,
    BLOCKED_CORRESPONDENCE_DELETED,
    UNBLOCKED,
    UNBLOCKED_CORRESPONDENCE_HIDDEN_FOR_RECIPIENT,
    UNBLOCKED_CORRESPONDENCE_HIDDEN_FOR_INTERLOCUTOR,
    UNBLOCKED_CORRESPONDENCE_HIDDEN_FOR_ALL
}
