export default [
    {
        val: 'TRAVEL',
        en: 'travelling',
        ru: 'путешествия',
        ua: 'мандрування',
    },
    {
        val: 'PLAYING_MUSIC_INSTRUMENTS',
        en: 'playing music instruments',
        ru: 'игра на музыкальных инструментах',
        ua: 'гра на музикальних iнструментах',
    },
    {
        val: 'DANCING',
        en: 'dancing',
        ru: 'танцы',
        ua: 'танцi',
    },
    {
        val: 'SINGING',
        en: 'singing',
        ru: 'пение/вокал',
        ua: 'спiв',
    },
    {
        val: 'PAINTING',
        en: 'painting art',
        ru: 'рисование',
        ua: 'малювання',
    },
    {
        val: 'OTHER_ARTS',
        en: 'other arts',
        ru: 'другие виды искусств',
        ua: 'iншi мистецтва',
    },
    {
        val: 'CHILDREN',
        en: 'child care',
        ru: 'дети',
        ua: 'дiти',
    },
    {
        val: 'CARS',
        en: 'cars',
        ru: 'автомобили',
        ua: 'автiвки',
    },
    {
        val: 'BICYCLES',
        en: 'bicycles',
        ru: 'велосипед',
        ua: 'велосипед',
    },
    {
        val: 'SCOOTERS',
        en: 'scooter riding',
        ru: 'катания на самокате/скутере, др.',
        ua: 'катання на самокатi/скутере, iн.',
    },
    {
        val: 'BOATING',
        en: 'boating',
        ru: 'катание на лодке',
        ua: 'катання на човнi',
    },
    {
        val: 'FISHING',
        en: 'fishing',
        ru: 'рыбалка',
        ua: 'рибальство',
    },
    {
        val: 'ENGINEERING',
        en: 'engineering, design',
        ru: 'инженерия, конструирование, дизайн',
        ua: 'iнженерiя, конструювання, дизайн',
    },
    {
        val: 'IT_COMPUTERS',
        en: 'it, computers',
        ru: 'it, компьютеры',
        ua: 'it, компьютори',
    },
    {
        val: 'GAMING',
        en: 'gaming',
        ru: 'компьютерные игры',
        ua: 'компьютернi iгри',
    },
    {
        val: 'ANIME',
        en: 'anime, cartoons',
        ru: 'аниме, мультяхи',
        ua: 'анiме, мультяхи',
    },
    {
        val: 'READING_BOOKS',
        en: 'reading books',
        ru: 'чтение книг',
        ua: 'книги',
    },
    {
        val: 'MOVIES',
        en: 'movies',
        ru: 'фильмы',
        ua: 'фiльми',
    },

];