package com.hub.accommodation.domain.user.enums;

public enum SeverityStatus {
    HOUSE_FULLY_DESTROYED, HOUSE_PARTLY_DESTROYED, HOUSE_MODERATELY_DAMAGED,
    HOUSE_UNTOUCHED_NO_HEAVY_FIGHTS_AROUND, HOUSE_UNTOUCHED_IN_WAR_ZONE, OTHER_REASON;
}


